language: java
jdk:
- openjdk11

install: "/bin/true"

script:
- |
  if [[ $TRAVIS_TAG =~ ^v.* ]]; then
    ./gradlew clean build publishP2Repo
  else
    ./gradlew clean build snapshot $(if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo "publishP2Repo"; fi)
  fi

